Legacy/estmtn/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import settings

from estimator.views import DashboardView, FeatureView, \
    RequirementDetailView, LegacyPageTreeListView, \
    EstimateView, EstimationResultView, CSVExprotView, \
    PageTreeListView
    
from estimator.utils import export

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'reidfaist.views.home', name='home'),
    # url(r'^reidfaist/', include('reidfaist.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^accounts/', include('registration.backends.default.urls')),


    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^requirements/$', LegacyPageTreeListView.as_view(), name='legacy'),
    url(r'^feature/(\w+)/$', FeatureView.as_view(), name='feature'),

    url(r'^estimate/$', EstimateView.as_view(), name='estimate'),
    url(r'^estimate/(?P<pk>\d+)/$', EstimateView.as_view(), name='estimate'),
    url(r'^results/$', EstimationResultView.as_view(), name='results'),

    url(r'^requirement/(?P<pk>\d+)/$', RequirementDetailView.as_view(), name='requirement'),
    url(r'^export/(?P<app_label>\w+)/(?P<model_name>\w+)/(?P<format>\w+)/$', admin.site.admin_view(export), {'admin_site': admin.site}),

    url(r'^pages/$', PageTreeListView.as_view(), name='page'),

    url(r'^csv/$', CSVExprotView.as_view(), name='csv'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.map_path('media'),
        }),
)

Legacy/estmtn/estimator/models.py
from django.db import models
from django.db.models import Q
from mptt.models import MPTTModel, TreeForeignKey
from django.db.models import Sum, Avg, Max

#from docx.docx import *

class Component(models.Model):
    """
    Top Level Component

    """
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name

class CoreFeature(models.Model):
    """
    Feature for components

    """
    name = models.CharField(max_length=255)
    component = models.ForeignKey(Component)
    photo = models.ImageField(upload_to='uploads/photos', blank=True)
    description = models.TextField(blank=True)
    deactivate = models.BooleanField()

    legacy_nodes = models.ManyToManyField("LegacyNode", blank=True, null=True)

    def __unicode__(self):
        return self.name

    def estimated(self):
        all_reqs = Requirement.objects.filter(core_feature=self).count()
        est_reqs = Requirement.objects.filter(~Q(points=''), core_feature=self).count()
        return str(est_reqs) + " / " + str(all_reqs)

DIFFICULTY_RATING= (
    ('0', '0'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('5', '5'),
    ('9', '9'),
    ('x', u"\u221E"),
)

STATUS_RATING= (
    ('1', 'Need'),
    ('2', 'Want'),
    ('3', 'Nice to Have'),
    ('5', 'Deprecated/Broken/NA'),
)

class Requirement(models.Model):
    """
    Requirement for feature

    """

    name = models.CharField(max_length=255)
    core_feature = models.ForeignKey(CoreFeature, blank=True, null=True)
    points = models.CharField(max_length=2, choices=DIFFICULTY_RATING, blank=True)
    priority = models.CharField(max_length=2, choices=STATUS_RATING, blank=True)
    description = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    deactivate = models.BooleanField()

    def __unicode__(self):
        return self.name


    
class EstimationMetric(models.Model):
    """
    Model for valuation of points

    """
    name = models.CharField(max_length=255, blank=True)
    hours_per_point = models.IntegerField()
    points_per_week = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return u"%04i hours per point" % self.hours_per_point


class LegacyNode(MPTTModel):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    site_photo = models.ImageField(upload_to='uploads/site_photos', blank=True)
    parent = TreeForeignKey("LegacyNode", blank=True, null=True, related_name='children')
    url = models.CharField(max_length=255, blank=True)
    form = models.BooleanField()

    def __unicode__(self):
        description = ''
        if self.description:
            description = "(%s)" % self.description

        if self.parent == None:
            return "%s %s" % (self.name, description)
        else:
            parent_description = ''
            if self.description:
                parent_description = "(%s)" % self.parent.description
            return "%s %s - %s %s" % (self.parent.name, parent_description, self.name, description)

    def count_forms(self):
        return LegacyNode.objects.filter(form=True).count()

    class MPTTMeta:
        order_insertion_by = ['name']


class Page(MPTTModel):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    site_photo = models.ImageField(upload_to='uploads/site_photos', blank=True)
    parent = TreeForeignKey("Page", blank=True, null=True, related_name='children')
    url = models.CharField(max_length=255, blank=True)
    form = models.BooleanField()

    def __unicode__(self):
        description = ''
        if self.description:
            description = "(%s)" % self.description

        if self.parent == None:
            return "%s %s" % (self.name, description)
        else:
            parent_description = ''
            if self.description:
                parent_description = "(%s)" % self.parent.description
            return "%s %s - %s %s" % (self.parent.name, parent_description, self.name, description)

    def estimate(self):
        stories = UserStory.objects.filter(pages=self)
        points = 0
        for story in stories:
            try:
                points = points+int(story.points)
            except:
                pass
        hours = points * 5
        if points:
            return str(hours) + 'hrs'
        else:
            return None

    def count_forms(self):
        return LegacyNode.objects.filter(form=True).count()

    class MPTTMeta:
        order_insertion_by = ['name']


class UserRole(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name
    
class UserStory(Requirement):
    story_id = models.CharField(max_length=255)
    user_role = models.ForeignKey(UserRole)

    in_scope = models.BooleanField()
    in_prd = models.BooleanField()

    follow_up = models.TextField(blank=True)

    duplicates = models.ManyToManyField("UserStory", blank=True, null=True)
    pages = models.ManyToManyField(Page, blank=True, null=True)
    estimation_metric = models.ForeignKey(EstimationMetric, blank=True, null=True)

    min = models.IntegerField(blank=True, null=True)
    exp = models.IntegerField(blank=True, null=True)
    max = models.IntegerField(blank=True, null=True)

    @property
    def effort(self):
        try:
            effort = int(self.points) * self.estimation_metric.hours_per_point
        except:
            effort = u"\u221E"
        return effort


    def __unicode__(self):
        return self.name
    
class LegacyBucket(models.Model):
    node = models.ForeignKey(LegacyNode)

    def __unicode__(self):
        return self.node.name

Legacy/estmtn/estimator/forms.py
from django import forms
from estimator.models import Requirement, UserStory

class RequirementForm(forms.ModelForm):
    class Meta:
        model = Requirement
        exclude = ('core_feature')

class UserStoryForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput)
    class Meta:
        model = UserStory
        exclude = ('core_feature')
        fields = ('id', 'name', 'story_id', 'user_role', 'points', 'priority', 'notes', 'deactivate')

Legacy/estmtn/estimator/views.py
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect

from estimator.models import CoreFeature, Requirement, \
    Component, LegacyNode, UserStory, Page
from estimator.forms import RequirementForm, UserStoryForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from django.contrib.admin.options import IncorrectLookupParameters
from django.contrib.admin.views.main import ChangeList
from django.http import HttpResponse, HttpResponseForbidden, Http404
from django.core.serializers import serialize
from django.template import loader, RequestContext
from django.template.defaultfilters import slugify
from django.db.models.loading import get_model
from django.utils.encoding import smart_str
import csv

__all__ = ('DashboardView', )

class LoginRequiredMixin(object):
    """
    View mixin which verifies that the user has authenticated.

    NOTE:
        This should be the left-most mixin of a view.
    """

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

class DashboardView(LoginRequiredMixin, ListView):
    """
    The main view with a top down view

    """
    context_object_name = "estimated_stories"
    template_name = "estimator/dashboard.html"
    queryset = UserStory.objects.exclude(points=u'')

class FeatureView(LoginRequiredMixin, ListView):
    """
    The main view with the pictures.

    """
    context_object_name = "requirement_list"
    template_name = "estimator/feature.html"

    def post(self, request, *args, **kwargs):
        form = RequirementForm(request.POST,)
        if form.is_valid():
            form.save()
            # do something.
        else:
            form = RequirementForm()

        return self.get(request, *args, **kwargs)

    def get_queryset(self):
        self.core_feature = get_object_or_404(CoreFeature, id=self.args[0])
        return Requirement.objects.filter(core_feature=self.core_feature)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(FeatureView, self).get_context_data(**kwargs)
        # Add in the publisher
        context['core_feature'] = self.core_feature
        #context['component_list'] = Component.objects.all()
        context['estimated_stories'] = UserStory.objects.exclude(points=u'')
        context['form'] = RequirementForm()
        return context

class RequirementDetailView(LoginRequiredMixin, DetailView):
    """
    The main view with the pictures.

    """
    context_object_name = "requirement"
    template_name = "estimator/requirement.html"
    queryset = Requirement.objects.all()

    def post(self, request, *args, **kwargs):
        form = RequirementForm(request.POST, instance=get_object_or_404(Requirement, id=self.kwargs['pk']))
        if form.is_valid():
            requirement = form.save(commit=False)
            requirement.core_feature = CoreFeature.objects.get(id=request.POST['core_feature'])

            requirement.save()
            # do something.
        else:
            form = RequirementForm()

        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(RequirementDetailView, self).get_context_data(**kwargs)
        #context['component_list'] = Component.objects.all()
        context['estimated_stories'] = UserStory.objects.exclude(points=u'')
        requirement = get_object_or_404(Requirement, id=self.kwargs['pk'])
        context['form'] = RequirementForm(instance=requirement)
        return context

class LegacyPageTreeListView(LoginRequiredMixin, ListView):

    context_object_name = "pages"
    template_name = "estimator/legacy_tree.html"
    queryset = LegacyNode.objects.all()

    def get_context_data(self, **kwargs):
        context = super(LegacyPageTreeListView, self).get_context_data(**kwargs)

        #context['component_list'] = Component.objects.all()
        context['estimated_stories'] = UserStory.objects.exclude(points=u'')
        context['nodes'] = self.queryset
        context['form_count'] = LegacyNode.objects.filter(form=True).count()
        return context

class PageTreeListView(LoginRequiredMixin, ListView):
    context_object_name = "pages"
    template_name = "estimator/page_tree.html"
    queryset = Page.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PageTreeListView, self).get_context_data(**kwargs)
        stories = UserStory.objects.all()
        points = 0
        for story in stories:
            try:
                points = points+int(story.points)
            except:
                pass
        hours = points * 5

        #context['component_list'] = Component.objects.all()
        context['estimated_stories'] = UserStory.objects.exclude(points=u'')
        context['nodes'] = self.queryset
        context['total_hours'] = hours
        context['form_count'] = LegacyNode.objects.filter(form=True).count()
        return context

class EstimateView(LoginRequiredMixin, ListView):
    context_object_name = "stories"
    template_name = "estimator/estimator.html"
    queryset = UserStory.objects.filter(points='')

    def post(self, request, *args, **kwargs):
        story = get_object_or_404(UserStory, id=request.POST.get('id'))
        form = UserStoryForm(request.POST, instance=story)
        if form.is_valid():
            form.save()
        else:
            form = RequirementForm(instance=story)

        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EstimateView, self).get_context_data(**kwargs)
        paginator = Paginator(self.queryset,1)

        try:
            stories = (UserStory.objects.get(id=self.kwargs['pk']), True)
        except:
            page = self.request.GET.get('page')
        
            try:
                stories = paginator.page(page)
            except PageNotAnInteger:
                # If page is not an integer, deliver first page.
                stories = paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999), deliver last page of results.
                stories = paginator.page(paginator.num_pages)

        context['form'] = UserStoryForm(instance=stories[0])
        context['estimated_stories'] = UserStory.objects.exclude(points=u'')
        context['story_id'] = stories[0].id

        context['stories'] = stories
        return context

class EstimationResultView(LoginRequiredMixin, ListView):
    context_object_name = "stories"
    template_name = "estimator/legacy_tree_doc.html"
    queryset = UserStory.objects.exclude(points=u'')

    def get_context_data(self, **kwargs):
        context = super(EstimationResultView, self).get_context_data(**kwargs)
        stories = UserStory.objects.exclude(points=u'').exclude(points=u'x')
        #import pdb; pdb.set_trace()
        total_points = 0
        for story in stories:
            total_points = total_points+int(story.points)
        context['total_points'] = total_points
        return context


class CSVExprotView(LoginRequiredMixin, ListView):

    def get(self, request, *args, **kwargs):
        c = RequestContext(self.request)
        model = UserStory
        #writer = csv.writer(open('media/documents/userstories.csv', 'wb'), quoting=csv.QUOTE_ALL)
        writer = []
        headers = ['Story ID', 'User Role', 'Story', 'Points', 'Status', 'Notes' ]
        writer.append(headers)
        for obj in model.objects.all().order_by("id"):
            row = [obj.story_id, obj.user_role.name, obj.name, obj.points, obj.get_status_display(), obj.notes]

            writer.append(row)

        t = loader.get_template('admin/export/csv')
        c['rows'] = writer
        responseContents = t.render(c)
        
        response = HttpResponse(responseContents, mimetype='text/csv')
        response['Content-Disposition'] = 'attachment; filename=user_stories.csv'

        return response

Legacy/estmtn/templates/estimator/component_list.html
    <div class="span3">
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
                {% for component in component_list %}
                    <li class="nav-header">{{ component.name }}</li>
                    {% for feature in component.corefeature_set.all %}
                        <li {% if core_feature.id == feature.id %}class="active"{% endif %}><a  href="{% url feature feature.id %}">{{ feature.name }} - {{ feature.estimated }}</a> </li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div><!--/.well -->
    </div><!--/span-->

Legacy/estmtn/templates/estimator/dashboard.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title%}Dashboard{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
{% include "estimator/estimated_stories_list.html" %}
    <div class="span9">
          <div class="hero-unit">
            <h2>eStmtn</h2>
            <p>Quick and easy agile project estimation.</p>
            <!--<p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>-->
          </div>
        </div>


{% endblock %}

Legacy/estmtn/templates/estimator/estimated_stories_list.html
    <div class="span3">
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
                <li class="nav-header">Estimated Stories</li>
                {% for story in estimated_stories %}
                    <li {% if story_id == story.id %}class="active"{% endif %}><a  href="{% url estimate story.id %}">{{ story.name }}</a> </li>

                {% endfor %}
            </ul>
        </div><!--/.well -->
    </div><!--/span-->


<!--
<div class="span3">
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
                {% for user_role in roles %}
                    <li class="nav-header">{{ user_role }}</li>
                    {% for story in user_role.userstories_set.all %}
                        <li {% if story_id == story.id %}class="active"{% endif %}><a  href="{% url estimate story.id %}">{{ story.name }}</a> </li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    </div>
-->

Legacy/estmtn/templates/estimator/estimator.html
{% extends "base.html" %}
{% load thumbnail %}
{% load mptt_tags %}
{% block title%}Estimator{% endblock %}

{% block extra_header %}

{% endblock %}

{% block extra_menu %}
{% endblock %}

{% block content %}
    {% include "estimator/estimated_stories_list.html" %}
<div class="span9">
    <div class="hero-unit">
    <span class="current">
         Page {{ stories.number }} of {{ stories.paginator.num_pages }}.
    </span>
    <form action="." method="post">
        <table class="table table-striped">
            {{ form.as_table }}
        </table>
        <table style="width: 100%">
            <tr>
                <td style="text-align: left;">

            <!-- Paginator Controls -->

            <span class="step-links">
                {% if stories.has_previous %}
                    <a class="btn" href="?page={{ stories.previous_page_number }}">previous</a>
                {% endif %}

                {% if stories.has_next %}
                    <a class="btn" href="?page={{ stories.next_page_number }}">next</a>
                {% endif %}
            </span>

        <!-- END Paginator Controls -->


                </td>
                <td style="text-align: right;">
                    {% csrf_token %}
                    <p><a class="btn btn-danger">Delete</a>  <button type="submit" class="btn btn-primary">Update</button></p>
                </td>
            </tr>
        </table>
    </form>



        
    </div>
</div>

{% endblock %}

Legacy/estmtn/templates/estimator/feature.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title%}Dashboard{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
    {% include "estimator/component_list.html" %}
        <div class="span9">
          <div class="hero-unit">
            <h1>{{ core_feature.name }}</h1>
            <p>{{ core_feature.description }}</p>
            <p><a class="btn btn-large">Edit Feature Info &raquo;</a></p>
          </div>


             {%  for requirement in core_feature.requirement_set.all %}
                
                {% cycle '<div class="row-fluid">' ''%}

                <div class="span5" style="border: solid 1px; border-color: #EEEEEE;">

                <table class="table table-striped">
                <tR>
                    <th colspan="2"><h3>{{ requirement.name }}</h3></th>
                </tR>
                <tr>
                    <th>Points:</th>
                    <td>{{ requirement.points }}</td>
                </tr>
                <tr>
                    <th>Status:</th>
                        <td>{{ requirement.status }}</td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td>{{ requirement.description|truncatewords:25 }} ...</td>
                </tr>
                <tr>
                    <th>Notes:</th>
                    <td>{{ requirement.description|truncatewords:25 }} ...</td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: right">
                        <p><a class="btn btn-info" href="{% url requirement requirement.id %}">Details &raquo;</a></p>
                    </td>
                </tr>
                </table>
                </div><!--/span-->
                {% cycle '' '</div><!-- endrow-->' %}




                 <!-- Create New Requirement -->



                {% if forloop.last %}

                {% if forloop.counter|divisibleby:2 %} <div class="row-fluid"> {% endif %}

                <div class="span5" style="border: solid 1px; border-color: #80B2FF;">
                <form action="." method="post">
                    <input name="core_feature" id="id_core_feature" type="hidden" value="{{ core_feature.id }}">
                <table class="table table-striped">
                <tR>
                    <th colspan="2"><h3>New Requirement</h3></th>
                </tR>
                <tr>
                    <th><label for="id_name">Name:</label></th>
                    <td><input id="id_name" type="text" name="name" maxlength="255" /></td>
                </tr>
                <tr>
                    <th><label for="id_points">Points:</label>
                    </th><td><select name="points" id="id_points">
                        <option value="" selected="selected">---------</option>
                        <option value="0">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="5">5</option>
                        <option value="9">9</option>
                        <option value="x">∞</option>
                    </select></td>
                </tr>
                <tr>
                    <th><label for="id_status">Status:</label></th>
                        <td><select name="status" id="id_status">
                            <option value="" selected="selected">---------</option>
                            <option value="0">Pointless</option>
                            <option value="1">Interesting</option>
                            <option value="2">Nice to Have</option>
                            <option value="3">Want</option>
                            <option value="5">Need</option>
                    </select></td>
                </tr>
                <tr>
                    <th><label for="id_description">Description:</label></th>
                    <td><textarea id="id_description" rows="3" cols="5" name="description"></textarea></td>
                </tr>
                <tr>
                    <th><label for="id_notes">Notes:</label></th>
                    <td><textarea id="id_notes" rows="3" cols="5" name="notes"></textarea></td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: right">
                        {% csrf_token %}
                         <button type="submit" class="btn btn-primary">Create Requirement</button>

                    </td>
                </tr>
                </table>
                </form>
                </div><!--/span-->

                </div><!-- endrow-->
                {% cycle '' '</div><!-- endrow-->' %}
                {% endif %}

                 <!-- END CREATE NEW REQUIREMENT -->

             {% endfor %}
        </div>

{% endblock %}

Legacy/estmtn/templates/estimator/legacy_tree_doc.html
{% extends "base.html" %}
{% load thumbnail %}
{% load mptt_tags %}

{% block extra_header %}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/prototype.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/scriptaculous.js?load=effects,builder"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/lightbox.js"></script>
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/lightbox.css" type="text/css" media="screen" />

    <script language="javascript">
        function addup(points, money, hours) {
            var points = document.getElementById("points");
	        var hours = document.getElementById("hours");
	        var money = document.getElementById("money");
            var total = document.getElementById("total");
            var velocity = document.getElementById("velocity");

            total.innerHTML = '$' + (points.value * hours.value * money.value) + '.00 | ' + (points.value / velocity.value) + ' weeks to completion.' ;
        }
    </script>
    
{% endblock %}

{% block extra_menu %}
<p><a id="displayText" class="navbar-text pull-right" href="{% url csv %}">Export CSV</a></p>
{% endblock %}

{% block content %}
    
    <table class="table table-striped">
        <tr>
            <th>Story ID</th>
            <th>User Role</th>
            <th>Story</th>
            <th>Points</th>
            <th>Status</th>
            <th>Notes</th>
            
        </tr>
        {% for story in stories %}
        <tr>
            <td>{{ story.story_id }}</td>
            <td>{{ story.user_role.name }}</td>
            <td>{{ story.name }}</td>
            <td>{{ story.get_points_display }}</td>
            <td>{{ story.get_status_display }}</td>
            <td>{{ story.notes }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="2">
                <table class="table table-striped">
                    <tr>
                        <th>Total Points:</th>
                        <td>
                            {{ total_points }}
                            <input id="points" name="points" type="hidden" value="{{ total_points }}">
                        </td>
                    </tr>
                    <tr>
                        <th>x hours per point</th>
                        <td>

                                <input id="hours" name="hours" type="text" class="span1" placeholder="hours">

                        </td>
                    </tr>
                    <tr>
                        <th>x dollars per hour</th>
                        <td>
                                <input id="money" name="money" type="text" class="span1" placeholder="$">
                        </td>
                    </tr>
                    <tr>
                        <th>velocity (points per week)</th>
                        <td>
                                <input id="velocity" name="velocity" type="text" class="span1" placeholder="-->">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <button type="submit"  OnClick="addup()"class="btn btn-primary">Estimate</button></p>
                        </td>
                        <td>
                            <div id="total"></div>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>


{% endblock %}

Legacy/estmtn/templates/estimator/requirement.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title%}Dashboard{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}
    {% include "estimator/estimated_stories_list.html" %}
        <div class="span9">
          <div class="hero-unit">
            <a href="{% url feature requirement.core_feature.id %}">{{ requirement.core_feature.name }}</a> > <b>{{ requirement.name }}</b>
                  <hr>
            <form action="." method="post">
                    <input name="core_feature" id="id_core_feature" type="hidden" value="{{ requirement.core_feature.id }}">
                    <table class="table table-striped">
                        {{ form.as_table }}
                            <td colspan="2" style="text-align: right">
                                {% csrf_token %}
                                <p><a class="btn btn-danger">Delete</a>  <button type="submit" class="btn btn-primary">Update</button></p>
                            </td>
                        </tr>
                    </table>
                </form>

          </div>



        </div>

{% endblock %}